### PR TITLE
Update quadriTab and minor changes

### PR DESCRIPTION
**Pull request by Delogen**
Update quadriTab and some minor faults

### CODE REVIEW

**Comment by blegat** [comment]
@philgreiner Any objection ? :)

**Comment by philgreiner** [comment]
None, you can merge :)

**Comment by Delogen** [comment]
There is two packages missing yet : 
\usepackage{adjustbox}
\usepackage{multirow} 
can you add them?

**Comment by blegat** [comment]
multirow is already added in eplbase.cls

**Pull request merged**
