### PR TITLE
Transport layer

### PR DESCRIPTION
**Pull request by Nhoutain**

### CODE REVIEW

**Comment by blegat** [comment]
I don't get it :P we said why did you remove the MAC from the datalink layer ? It is a datalink layer principle isn't it ?

**Comment by blegat** [comment]
We said we would split Principles and Protocols into layers :)

**Comment by Nhoutain** [comment]
Je trouve ca plus parlant dans sharing ressource :) au pire c'est juste un
copier coller à changer :p

**Comment by blegat** [comment]
Ok... :P

**Pull request merged**
