### PR TITLE
LMAT2450 Crypto exercises

### PR DESCRIPTION
**Pull request by TGLuis**
During the quadrimester, we have written some solution from the base of the previous ones. But the exercises where slightly different so here is the last version of the exercises with the solutions we made. I asked the teaching assistant Pierrick Méaux to have the statements of the exercises, he accepted so I merged the two documents.

### CODE REVIEW

**Comment by blegat** [comment]
What did you do of the solutions that didn't match any exercise from this year ?

**Comment by TGLuis** [comment]
As I don't have the statements, I did not put them in the document. Do you have another solution?

**Comment by blegat** [comment]
Could you put them in a separate file with a TODO comment that these are solutions from a previous year from which we are missing the statement. I may be able to find the statements from the previous years

**Comment by TGLuis** [comment]
Ok sure, i will do that. :)

**Pull request closed without merging**
